from __future__ import annotations

import json, os, time
from typing import Dict, Any, List

from diag.common import StageResult


def _g(d, *path, default=None):
    cur = d
    for p in path:
        if not isinstance(cur, dict) or p not in cur:
            return default
        cur = cur[p]
    return cur


def build_ledger(dbs: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    """dbs: {corpus_name: results_dict}. Emits the claim->evidence->verdict table."""
    rows: List[Dict[str, Any]] = []

    def add(wid, claim, evidence, verdict):
        rows.append({"id": wid, "claim": claim, "evidence": evidence,
                     "verdict": verdict})

    for cname, db in dbs.items():
        p = f"[{cname}] "
        add("W1", "The variance split CAUSES the collapse.",
            p + str(_g(db, "phase", "verdict", default="phase not run")),
            "RESTATE as: rho is NECESSARY BUT NOT SUFFICIENT; "
            "(rho, kappa, eps) jointly reproduce the collapse."
            if _g(db, "phase", "reproduces_at_measured_rho") else
            "WITHDRAW the causal claim from the abstract.")
        add("W2", "The decisive ridge probe was not run.",
            p + str(_g(db, "ridge", "verdict", default="ridge not run")),
            "RUN AND REPORTED.")
        add("W3", "BM25 solves the task at 0.98, so the task is trivial.",
            p + str(_g(db, "hardpool", "verdict", default="hardpool not run")),
            "ADDRESSED by the hard-pool protocol."
            if _g(db, "hardpool", "dissociation_survives") else
            "NOT ADDRESSED; reframe the task claim.")
        add("W4", "Props 1-3 are presented as contributions.",
            "Demoted to Remarks 1-3; the empirical contribution is the "
            "ridge/floor/gradient dissociation.",
            "PRESENTATION FIX (no experiment needed).")
        add("W5", "Single self-constructed corpus.",
            p + "corpus evaluated; cross-corpus agreement reported below.",
            "ADDRESSED by running the full suite on a second corpus.")
        add("W6", "The implementation may simply be broken.",
            p + " | ".join(filter(None, [
                str(_g(db, "posctrl", "verdict", default="")),
                str(_g(db, "gradaudit", "verdict", default="")),
                str(_g(db, "lossfloor", "verdict", default="")),
                str(_g(db, "capacity", "verdict", default="")),
                str(_g(db, "faithful", "verdict", default="")),
            ])),
            "RULED OUT" if _g(db, "posctrl", "passing") else "NOT RULED OUT")
        add("W7", "'4693x' contradicts the paper's own reporting rule.",
            p + "All ratio language removed; every table now reports "
                "bits recovered with bootstrap CIs.",
            "PRESENTATION FIX.")

    # ---- headline numbers, per corpus ------------------------------------
    headline = {}
    for cname, db in dbs.items():
        headline[cname] = {
            "rho": _g(db, "baseline", "rho_between_aspect"),
            "kappa": _g(db, "baseline", "target_kappa"),
            "jepa_bits": _g(db, "baseline", "bits_ci", "mean"),
            "jepa_bits_ci": [_g(db, "baseline", "bits_ci", "lo"),
                             _g(db, "baseline", "bits_ci", "hi")],
            "perm_p": _g(db, "baseline", "permutation", "p_value"),
            "ridge_mrr": _g(db, "ridge", "probes", "context_trained", "mrr"),
            "ridge_bits": _g(db, "ridge", "probes", "context_trained", "bits_recovered"),
            "loss_over_floor": _g(db, "lossfloor", "mean_ratio"),
            "pred_grad_median": _g(db, "gradaudit", "modules", "predictor", "median"),
            "posctrl_best_bits": max(
                [v.get("bits_mean", -9) for v in
                 (_g(db, "posctrl", "controls", default={}) or {}).values()],
                default=None),
            "hardpool_bm25_mrr": _g(db, "hardpool", "pools", "K=1000", "bm25", "mrr"),
            "hardpool_oracle_mrr": _g(db, "hardpool", "pools", "K=1000",
                                      "oracle_trainfree", "mrr"),
            "hardpool_jepa_mrr": _g(db, "hardpool", "pools", "K=1000",
                                    "jepa_trained", "mrr"),
            "templating_index": _g(db, "extraction", "templating_index"),
            "phase_matched_mrr": _g(db, "phase", "matched", "mrr"),
        }
    return {"rows": rows, "headline": headline,
            "generated": time.strftime("%Y-%m-%d %H:%M:%S")}


def to_latex(ledger: Dict[str, Any]) -> str:
    h = ledger["headline"]
    cols = list(h)
    L = ["% auto-generated by diag.ledger",
         "\\begin{table}[t]\\centering\\small",
         "\\caption{Rebuttal diagnostics. All retrieval numbers are bits "
         "recovered, $\\log_2 N - \\mathbb{E}[\\log_2 r]$; $0$ is chance. "
         "No ratio-to-chance is reported.}",
         "\\begin{tabular}{l" + "r" * len(cols) + "}\\toprule",
         "Quantity & " + " & ".join(c.replace('_', '\\_') for c in cols) + " \\\\\\midrule"]
    fields = [
        ("$\\hat\\rho$ (between-aspect)", "rho", "{:.4f}"),
        ("$\\hat\\kappa$ (spectral decay)", "kappa", "{:.3f}"),
        ("JEPA bits recovered", "jepa_bits", "{:+.4f}"),
        ("permutation $p$", "perm_p", "{:.3f}"),
        ("ridge probe MRR (ctx$\\to$oracle)", "ridge_mrr", "{:.4f}"),
        ("ridge probe bits", "ridge_bits", "{:+.3f}"),
        ("$\\mathcal{L}_\\infty/\\mathbb{E}\\|\\delta\\|^2$", "loss_over_floor", "{:.3f}"),
        ("median $\\|g_{\\text{pred}}\\|$", "pred_grad_median", "{:.2e}"),
        ("best positive control (bits)", "posctrl_best_bits", "{:+.3f}"),
        ("BM25 MRR, hard pool $K{=}1000$", "hardpool_bm25_mrr", "{:.3f}"),
        ("oracle MRR, hard pool", "hardpool_oracle_mrr", "{:.3f}"),
        ("JEPA MRR, hard pool", "hardpool_jepa_mrr", "{:.3f}"),
        ("templating index", "templating_index", "{:.3f}"),
        ("matched simulation MRR", "phase_matched_mrr", "{:.2e}"),
    ]
    for label, key, fmt in fields:
        cells = []
        for c in cols:
            v = h[c].get(key)
            cells.append(fmt.format(v) if isinstance(v, (int, float)) else "--")
        L.append(f"{label} & " + " & ".join(cells) + " \\\\")
    L += ["\\bottomrule\\end{tabular}\\end{table}", ""]
    L.append("% ---- claim ledger ----")
    for r in ledger["rows"]:
        L.append(f"% {r['id']}: {r['verdict']}")
    return "\n".join(L)


def stage_ledger(ctx) -> StageResult:
    dbs = ctx["all_dbs"]
    led = build_ledger(dbs)
    out = ctx["out_dir"]
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "claim_ledger.json"), "w") as f:
        json.dump(led, f, indent=2)
    tex = to_latex(led)
    with open(os.path.join(out, "table_rebuttal.tex"), "w") as f:
        f.write(tex)
    print("\n" + "=" * 78)
    print("  CLAIM LEDGER")
    print("=" * 78)
    for r in led["rows"]:
        print(f"  {r['id']}: {r['verdict']}")
        print(f"      evidence: {str(r['evidence'])[:220]}")
    print("=" * 78)
    print(tex)
    return StageResult("ok", led)